"""empty message

Revision ID: 255dc86f7683
Revises: 
Create Date: 2019-02-03 11:41:21.877356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255dc86f7683'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coastertracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coaster', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('inversions', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('elements', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.String(length=10), nullable=True),
    sa.Column('verticalAngle', sa.Integer(), nullable=True),
    sa.Column('drop', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coaster'], ['coasterrides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('coasterwaittimes', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.add_column('coasterwaittimes', sa.Column('earlyEntry', sa.Boolean(), nullable=True))
    op.add_column('coasterwaittimes', sa.Column('humidity', sa.Integer(), nullable=True))
    op.add_column('coasterwaittimes', sa.Column('windspeed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coasterwaittimes', 'windspeed')
    op.drop_column('coasterwaittimes', 'humidity')
    op.drop_column('coasterwaittimes', 'earlyEntry')
    op.drop_column('coasterwaittimes', 'datetime')
    op.drop_table('coastertracks')
    # ### end Alembic commands ###
