"""empty message

Revision ID: 4e65cfa905f7
Revises: 9a8bccacbfed
Create Date: 2019-04-30 21:11:59.102234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e65cfa905f7'
down_revision = '9a8bccacbfed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastRun', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('lastRun')

    # ### end Alembic commands ###
