"""empty message

Revision ID: 9a8bccacbfed
Revises: 255dc86f7683
Create Date: 2019-02-03 13:09:28.179730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8bccacbfed'
down_revision = '255dc86f7683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coasterrides', schema=None) as batch_op:
        batch_op.drop_column('make')
        batch_op.drop_column('modelLayout')
        batch_op.drop_column('coasterType')
        batch_op.drop_column('configuration')
        batch_op.drop_column('modelCategory')

    with op.batch_alter_table('coastertracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coasterType', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('configuration', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('make', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('modelCategory', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('modelLayout', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coastertracks', schema=None) as batch_op:
        batch_op.drop_column('modelLayout')
        batch_op.drop_column('modelCategory')
        batch_op.drop_column('make')
        batch_op.drop_column('configuration')
        batch_op.drop_column('coasterType')

    with op.batch_alter_table('coasterrides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelCategory', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('configuration', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('coasterType', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('modelLayout', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('make', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
