"""empty message

Revision ID: c14373989cf2
Revises: 
Create Date: 2019-01-31 08:48:34.324292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14373989cf2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('pythonFile', sa.String(length=53), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('cronString', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coasterwaittimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park', sa.Integer(), nullable=True),
    sa.Column('ride', sa.Integer(), nullable=True),
    sa.Column('waitTime', sa.Integer(), nullable=True),
    sa.Column('weather', sa.String(length=40), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['park'], ['coasterparks.id'], ),
    sa.ForeignKeyConstraint(['ride'], ['coasterrides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coasterwaittimes')
    op.drop_table('jobs')
    # ### end Alembic commands ###
