"""empty message

Revision ID: f21e0d00de32
Revises: 
Create Date: 2019-01-26 14:06:17.435236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21e0d00de32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coasterparks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('rcdbID', sa.Integer(), nullable=True),
    sa.Column('wikipediaLink', sa.String(length=500), nullable=True),
    sa.Column('abbrev', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coasterrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('rcdbID', sa.Integer(), nullable=True),
    sa.Column('wikipediaLink', sa.String(length=500), nullable=True),
    sa.Column('ridden', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['park'], ['coasterparks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coasterrides')
    op.drop_table('coasterparks')
    # ### end Alembic commands ###
